#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".
echo "generating git change log for latex"
echo "script is being run from $PWD"
cd src/ && ./makegit.pl

