#!/usr/bin/perl

use Switch;

use Texmake::Colorizer;
use Texmake::MakeMaker;
use Texmake::Builder;
use Texmake::Printer qw(print_w print_e print_f print_n);

# first, make sure that we have at least one argument
if( ($#ARGV + 1) < 1)
{
    print_f "Not enough arguments";
    print_help();
    die;
}

$command = shift(@ARGV);

switch($command)
{
    case "init"
    {
        my $init = Texmake::MakeMaker->new(@ARGV);
        $init->go();
    }
    
    case "build"
    {
        my $builder = Texmake::Builder->new(@ARGV);
        $builder->go();
    }
    
    case "color"
    {
        my $colorizer = Texmake::Colorizer->new(@ARGV);
        $colorizer->go();
    }
    
    default
    {
        print_f "Unrecognized command $command";
        print_help();
    }
}



sub print_help
{
    print_e <<END;
usage: $0 [command] [args]

COMMANDS
    init    initialize the texmake build directory and creates the makefile
    build   builds the specified file
    color   colorizes output 
END
}